# Generated by Django 4.1 on 2023-07-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
