# Generated by Django 4.1 on 2023-07-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0017_image__transparent'),
        ('astra', '0003_alter_menu_options_menu_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('disclaimer', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_company', to='filer.file')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_company', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
