# Generated by Django 4.1 on 2023-07-18 18:47

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('astra', '0004_plus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plus',
            options={'ordering': ['order'], 'verbose_name': 'приемущество', 'verbose_name_plural': 'Приемущества'},
        ),
        migrations.RemoveField(
            model_name='plus',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='plus',
            name='logo',
        ),
        migrations.AddField(
            model_name='plus',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
